# SPDX-FileCopyrightText: 2026 Yaroslav Yudaev <ydaevy10@gmail.com>
# SPDX-License-Identifier: MIT

"S: Needs Review":
- base-branch: '.*'

"S: Awaiting Changes":
- base-branch: '^$'

"S: Approved":
- base-branch: '^$'
