- type: antag
  id: Nightmare
  name: role-antag-nightmare-name
  antagonist: true
  setPreference: false
  objective: roles-antag-nightmare-objective

- type: antagSpecifier
  id: Nightmare
  prefRoles:
  - Nightmare
  pickPlayer: false
  spawnerPrototype: SpawnPointGhostNightmare
  mindRoles:
  - MindRoleGhostRoleSoloAntagonist

- type: startingGear
  id: NightmareGear
  inhand:
    - NightmareArmBlade
