name: "Labels: Needs Review"

on:
  pull_request_target:
    types: [opened, reopened, ready_for_review, review_requested, synchronize]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  needs_review:
    if: github.actor != 'Erida-change-bot' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Mark PR as needing review
        uses: step-security/action-add-labels@v1.1.1
        with:
          number: ${{ github.event.pull_request.number }}
          labels: "S: Needs Review"

      - name: Remove stale review state labels
        uses: step-security/action-remove-labels@v1.3.1
        with:
          number: ${{ github.event.pull_request.number }}
          labels: |
            S: Awaiting Changes
            S: Approved
