name: "Labels: Size"
on:
  pull_request_target:
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  size-label:
    if: github.actor != 'Erida-change-bot' && github.event.pull_request.draft == false
    permissions:
      contents: read
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: size-label
        uses: "pascalgn/size-label-action@v0.5.7"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          # Custom size configuration
          sizes: >
            {
              "0": "XS",
              "10": "S",
              "100": "M",
              "1000": "L",
              "5000": "XL"
            }
