name: "Labels: Needs Review"

on:
  pull_request_target:
    types: [opened, reopened, ready_for_review, review_requested, synchronize]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  needs_review:
    if: github.actor != 'Erida-change-bot' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Mark PR as needing review
        uses: actions/labeler@v6.1.0
        with:
          configuration-path: .github/labeler-review-state.yml
          sync-labels: true
