name: "Labels: Awaiting Changes"

on:
  pull_request_review:
    types:
      - submitted

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  awaiting_changes:
    if: >
      github.repository == 'dead-space-server/space-erida-14' &&
      github.event.review.state == 'changes_requested' &&
      github.event.pull_request.user.login != 'Erida-change-bot' &&
      github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Mark PR as awaiting changes
        uses: step-security/action-add-labels@v1.1.1
        with:
          number: ${{ github.event.pull_request.number }}
          labels: "S: Awaiting Changes"

      - name: Remove stale review state labels
        uses: step-security/action-remove-labels@v1.3.1
        with:
          number: ${{ github.event.pull_request.number }}
          labels: |
            S: Needs Review
            S: Approved
